### ISSUE TITLE
IncompatibleClassChangeError when running any query on xlsx file

### ISSUE THREAD

**Issue by drish** [bizreach/drill-excel-plugin#1]
hello !

first of all thanks for this plugin, it seems really promising.

I followed the steps on installing the plugin locally, but when I try to run a query on a xlsx file, I get the following error.

`org.apache.drill.common.exceptions.UserRemoteException: SYSTEM ERROR: IncompatibleClassChangeError: Found interface org.apache.drill.exec.ops.FragmentContext, but class was expected Fragment 0:0 [Error Id: c3b71d5d-4194-4a6b-a9c6-ed43f7e0a6c9 on a0d18aa6bfe0:31010]`

Drill Version: 1.14

have you guys run through anything similar ?

**Comment by drish** [comment]
it seems to be a problem with newer versions of drill. `1.13`+
tested with 1.12 and it works.

**Comment by shimamoto** [comment]
@drish 1.1.0 has been released. I checked it works with Drill 1.14.0 as well. Could you try it?

**Comment by drish** [comment]
@shimamoto @takezoe works ! thanks for the quick response !
